<p> <a href="<?php echo $this->baseUrl('admin/add'); ?>"> Add User </a></p>

<table id="user_list">
	<tr>
		<td><b>Firstname</b></td>
		<td><b>Lastname</b></td>
		<td><b>Email</b></td>
		<td><b>Update</b></td>
		<td><b>Edit</b></td>
	</tr>
	<?php foreach($this->entries as $users): ?>
	<tr>

	<td> <?php echo $this->escape($users->firstname); ?></td>
	<td> <?php echo $this->escape($users->lastname); ?></td>
	<td> <?php echo $this->escape($users->email) ?></td>
	<td> <a href="<?php echo $this->baseUrl('admin/edit'); ?>/id/<?php echo $this->escape($users->id);?>">update</a>
	<td>
	<a href="<?php echo $this->baseUrl('admin/delete');?>/id/<?php echo $this->escape($users->id);?>">delete</a>
	</td>
	</tr>

	<?php endforeach; ?>
</table>