<?php
if(isset($this->errorMessage))
{
echo $this->errorMessage;
}
?>

<center>
<div class ="user_form">
<h1>Sign in</h1>

<?php
	echo $this->form;
?>
</div>
Don't have an account? <a href="<?php echo $this->url(
        array(
            'controller' => 'index',
            'action'     => 'signup'
        ))?>">Create one.</a><br>
<a href="<?php echo $this->url(
        array(
            'controller' => 'index',
            'action'     => 'forgottenpassword'
        ))?>">Forgot Password</a>

</center>
