<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Quickstart Application</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
  <script src="http://ajax.microsoft.com/ajax/jquery.validate/1.7/additional-methods.js"></script>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.js"></script>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
   <?php echo $this->headScript()->appendFile('/js/script.js'); ?>
</head>
<body>
<div id="header">
    <div id="header-logo" style="float: left">
      <a id="navbar-brand" href="/"><img src="<?php echo $this->baseUrl();?>/images/zend-framework-logo.svg" /></a>
    </div>
    <div id="header-navigation" style="float: right">
    </div>

    <?php
    $identity = Zend_Auth::getInstance()->getIdentity();
    if($identity){ ?>
      <a style="float: right;margin:20px;" href="<?php echo $this->url(
      array(
          'controller' => 'index',
          'action'     => 'logout'
      ))?>">Logout</a>
    <?php
    } 
    else { ?>
     <a style="float: right;margin:10px;display:inline;" href="<?php echo $this->url(
      array(
          'controller' => 'index',
          'action'     => 'index'
      ))?>">Login</a>

  <?php  
  }
?>
    
</div>
<div id="container">
  <?php echo $this->layout()->content ?>
</div>

<div id="footer">
    
</div>

</body>
</html>

